### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading '0')

### ISSUE THREAD

**Issue by mattjared** [Basedash/dockhunt-cli#1]
When I run the dockhunt app I get the following error....

```
Scanning your dock...

node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

TypeError: Cannot read properties of undefined (reading '0')
    at getAppNamesToIconPaths (/snapshot/dist/index.cjs)
    at getDockContents (/snapshot/dist/index.cjs)
```

When I run the CLI I get this error....

```
const appDirectoryUrl = parsedAppData.dict[0].dict[0].string[0];
                                                          ^
TypeError: Cannot read properties of undefined (reading '0')
```

My working theory is that I have intentionally added in spaces in my dock that don't show as apps and that breaks the script that gets the app icons. 

How to add spaces: https://dev.to/shadowfaxrodeo/til-how-to-add-spaces-to-the-dock-on-macos-m50.

**Comment by jeremysarchet** [comment]
Woah @mattjared! I had no idea you could do such a thing as put "spaces" in your dock. That's wild. Would be cool to support "spaces" in Dockhunt.

**Comment by jeremysarchet** [comment]
As you can see (in proper hackathon style) we've hard-coded the nested properties in the XML plist files to get at the app names and the paths to their icons on the Mac. So, my guess is that in your XML, for the "spacer" item, there's no `string` array there giving you the path to the "App bundle directory" (where we go to look for the icon file).

**Comment by jeremysarchet** [comment]
If you're in the mood for it, feel free to open a PR to gracefully handle the case of "spacers".
