### ISSUE TITLE
Icon: Tweek app

### ISSUE THREAD

**Issue by bogdaaamn** [Basedash/dockhunt-cli#13]
Heyyy! First of all, amazing work folks, this is an awesome product 😭😭 

Quite random app, but is there any chance you can update the Tweek app icon?

https://www.dockhunt.com/apps/Tweek

> **Tweek**
> Fast and minimal weekly calendar app
>
> https://tweek.so/
> https://twitter.com/tweekHQ

Unfortunately I couldn't find any `.icns` file in the package contents. It seems like a React Native built app, so all I could find are some `.png`s, would these be enough?

[AppIcon60x60@2x.png.zip](https://github.com/Basedash/dockhunt-cli/files/10560427/AppIcon60x60%402x.png.zip)

**Comment by robertcoopercode** [comment]
Updated!

https://www.dockhunt.com/users/BogdanCovrig

**Comment by bogdaaamn** [comment]
Thank you @robertcoopercode 🫶🏼🫶🏼
