### ISSUE TITLE
Icons for some apps display incorrectly

### ISSUE THREAD

**Issue by thejustinwalsh** [Basedash/dockhunt-cli#3]
The icons for Rider and Blender render incorrectly on dockhunt.com
https://www.dockhunt.com/users/thejustinwalsh

![image](https://user-images.githubusercontent.com/72912/215874335-c57c11d8-d00f-491d-9726-3a0273cb2c17.png)

![image](https://user-images.githubusercontent.com/72912/215874291-5ca876cb-834b-4ea0-b290-8cf058f92b55.png)

Let me know if there is any other info that would be helpful to provide.

**Comment by robertcoopercode** [comment]
If you could send us the `.icns` file corresponding with those apps, I can update the image in our database to be the correct one.

To do that, open the app in your finder and right click on it. Select "Show package contents" and then try to find a `.icns` file somewhere. Taking Figma as an example it is found in `Contents` -> `Resources`.

<img width="368" alt="image" src="https://user-images.githubusercontent.com/16786990/215883771-f68d8ba8-e1bc-4823-92c3-6bdc927d1c59.png">

![CleanShot 2023-01-31 at 16 12 33@2x](https://user-images.githubusercontent.com/16786990/215884442-8452cf9c-83fe-45d5-9ec9-15d5503e768a.png)

**Comment by thejustinwalsh** [comment]
[rider.icns.zip](https://github.com/Basedash/dockhunt-cli/files/10551164/rider.icns.zip)
[blender icon.icns.zip](https://github.com/Basedash/dockhunt-cli/files/10551166/blender.icon.icns.zip)

**Comment by robertcoopercode** [comment]
Thank you! Fixed!

https://www.dockhunt.com/users/thejustinwalsh
