### ISSUE TITLE
Incorrect Icon of Microsoft Outlook and Sublime Text

### ISSUE THREAD

**Issue by oscargong** [Basedash/dockhunt-cli#4]
App name: Microsoft Outlook (com.microsoft.Outlook)
Check the second icon on the dock: https://www.dockhunt.com/users/oscargong1995

App name: Sublime Text (com.sublimetext.4)
Also check: https://www.dockhunt.com/users/oscargong1995

I attached the correct Icon. 
Github doesn't allow icns type attachment, I compressed it.

[Outlook.icns.zip](https://github.com/Basedash/dockhunt-cli/files/10553242/Outlook.icns.zip)
[Sublime Text.icns.zip](https://github.com/Basedash/dockhunt-cli/files/10553533/Sublime.Text.icns.zip)

**Comment by jeremysarchet** [comment]
Hi @oscargong, thank you for opening this issue. The scanning code is completely naive and basic. It looks for the first icon file (file ending in `.icns`) it finds in the `<YourApp>.app/Contents/Resources` directory of your app.

So, we've seen a few cases where an an app has multiple `.icns` files in there. Perhaps this has happened with your Outlook and Sublime Test.

We've also seen a few cases (Happened to me with Firefox), where somehow the `.icns` file in there is not cropped to a rounded rectangle in the classic way that the macOS dock has, but rather it's some other shape (in the case I had with Firefox, it was a rectangle, like a sheet of paper, with the corner curved down).

So, what we've done in such cases is to go into our DB and manually correct the problem icons. I'll do this for your two now.

**Comment by jeremysarchet** [comment]
Done. Thank you for attaching the two icons in question here. I downloaded them, converted them to PNG and replaced them in our db. Now if you go to your dock again they are looking good.

You can also see them here looking good:
https://www.dockhunt.com/apps/Microsoft%20Outlook
https://www.dockhunt.com/apps/Sublime%20Text
