### ISSUE TITLE
Catalyst apps throw a runtime error

### ISSUE THREAD

**Issue by raxityo** [Basedash/dockhunt-cli#7]
The Catalyst apps (iPad apps compatible with apple machines running on Apple Silicon) don't have the same structure as native MacOS apps, so the lookup for icons fails for these apps since AppName.app/Contents/Resources directory doesn't exist for these apps.

**Comment by jeremysarchet** [comment]
Thanks @raxityo, for opening this issue. Woah. Just this morning I learned of the possibility of running iOS apps on macOS and having them in your dock. Now I've just learned of the existence of Mac Catalyst. Ok, yes we shall improve the CLI tool to at the very least handle this more gracefully. Ideally, we support them outright.

**Comment by raxityo** [comment]
Thanks for considering this feature request, @jeremysarchet :) I took the liberty to help out with this feature and opened PR #9, #11.


For some reason, my dock doesn't show up entirely after I added my catalyst app through the patched CLI https://www.dockhunt.com/users/raxityo. (Oops!) I hope the error logs would be helpful in finding the underlying problem.
